services:
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - ./app/events.json:/app/events.json
    environment:
      - TZ=Asia/Bangkok
    restart: unless-stopped
    networks:
      - appnet
  nginx:
    image: nginx:1.27-alpine
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "8880:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
